cliente_rfc: "REM150313D57" 

base_path: "clientes/${cliente_rfc}"

cer_path: "${base_path}/certificados/cert.pem"
key_path: "${base_path}/certificados/fiel.pem"
pfx_password_path: "${base_path}/certificados/password.txt"

token_path: "${base_path}/tokens/token.txt"

rfc: "${cliente_rfc}"

endpoints:
  autenticacion: "https://cfdidescargamasivasolicitud.clouda.sat.gob.mx/Autenticacion/Autenticacion.svc"
  autenticacion_action: "http://DescargaMasivaTerceros.gob.mx/IAutenticacion/Autentica"

  solicitud: "https://cfdidescargamasivasolicitud.clouda.sat.gob.mx/SolicitaDescargaService.svc"
  solicitud_action: "http://DescargaMasivaTerceros.sat.gob.mx/ISolicitaDescargaService/SolicitaDescarga"

  verificacion: "https://cfdidescargamasivasolicitud.clouda.sat.gob.mx/VerificaSolicitudDescargaService.svc"
  verificacion_action: "http://DescargaMasivaTerceros.sat.gob.mx/IVerificaSolicitudDescargaService/VerificaSolicitudDescarga"

  descarga: "https://cfdidescargamasiva.clouda.sat.gob.mx/DescargaMasivaService.svc"
  descarga_action: "http://DescargaMasivaTerceros.sat.gob.mx/IDescargaMasivaTercerosService/Descargar"

fechas:
  inicio: "2024-02-01"
  fin: "2024-06-30"

descarga:
  tipo_solicitud: "Metadata"
  tipo_comp: "E"
  rfc_emisor: "${cliente_rfc}"
